### ISSUE TITLE
Can we replace hardcoded domain with {{DOMAIN_NAME}}?

### ISSUE THREAD

**Issue by kamoljan** [By-DevOps-For-DevOps/microservice-nodejs#33]
https://github.com/microservices-today/ngp-nodejs/blob/4980cd19159e36b7170db5ed54e9ac41aeff1340/swagger.yaml#L9

@wooiliang

**Comment by wooiliang** [comment]
Issue fixed. https://github.com/microservices-today/ngp-nodejs/commit/35946e84b1e470f35207e9dbc50055d0ca8540c9
Thank you @kamoljan

**Comment by wooiliang** [comment]
https://github.com/microservices-today/ngp-app-codepipeline/pull/50
https://github.com/microservices-today/ecs-api/commit/b8ee20bdecbaf65341319d3e218bf8ee034ee9d5
